# Generated by Django 5.2.5 on 2025-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField(blank=True)),
                ("first_name", models.TextField(blank=True)),
                ("street_number", models.TextField(blank=True)),
                ("street_name", models.TextField(blank=True)),
                ("apartment_number", models.TextField(blank=True)),
                ("zip_code", models.TextField(blank=True)),
                ("date_of_birth", models.DateTimeField(blank=True)),
                ("date_of_registration", models.DateTimeField(blank=True)),
                ("party_of_registration", models.TextField(blank=True)),
                ("precinct_number", models.TextField(blank=True)),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
                ("voter_score", models.IntegerField(default=0)),
            ],
        ),
    ]
