# Generated by Django 5.2.5 on 2025-10-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="party_of_registration",
            new_name="party_affliation",
        ),
    ]
