# Generated by Django 5.2.5 on 2025-10-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_alter_voter_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="party_affliation",
            new_name="party_affiliation",
        ),
    ]
