# Generated by Django 5.2.6 on 2025-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_post_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="timestamp",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(blank=True),
        ),
    ]
