# Generated by Django 5.2.5 on 2025-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_alter_photo_timestamp_alter_post_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
