# Generated by Django 5.2.5 on 2025-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuisinetype",
            name="api_identifier",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cuisinetype",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
